<!DOCTYPE html>
<html lang="ru">
  <head>
    <title>10. Обработка ошибок</title>
    <meta charset="UTF-8" />
    <script
      src="https://code.jquery.com/jquery-3.4.1.min.js"
      integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo="
      crossorigin="anonymous"
    ></script>
    <script src="../js/main.js"></script>
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
      integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
      crossorigin="anonymous"
    />
    <script
      src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
      integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
      integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
      integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
      crossorigin="anonymous"
    ></script>

    <style>
      xmp {
        font-family: inherit;
      }
      pre {
        background: #f5f2f0;
        padding: 16px;
        border-radius: 8px;
        white-space: break-spaces;
      }

      .card-body div:last-child,
      .card-body ul:last-child,
      .card-body ol:last-child,
      .card-body pre:last-child ,
      .card-body p:last-child {
          margin-bottom: 0;
      }
    </style>
  </head>
  <body class="pt-5">
    <nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top">
      <div class="container">
        <button
          class="navbar-toggler"
          type="button"
          data-toggle="collapse"
          data-target="#navbarNavDropdown"
          aria-controls="navbarNavDropdown"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <ul class="navbar-nav">
            <li class="nav-item dropdown">
              <a
                class="nav-link dropdown-toggle"
                href="#"
                id="navbarDropdownMenuLink1"
                role="button"
                data-toggle="dropdown"
                aria-haspopup="true"
                aria-expanded="false"
              >
                JavaScript</a
              >
              <div
                class="dropdown-menu"
                aria-labelledby="navbarDropdownMenuLink1"
              >
                <a class="dropdown-item" href="/dist/1-intro.html"
                  >1. Введение</a
                >
                <a class="dropdown-item" href="/dist/2-first-steps.html"
                  >2. Основы JavaScript</a
                >
                <a class="dropdown-item" href="/dist/3-code-quality.html"
                  >3. Качество кода</a
                >
                <a class="dropdown-item" href="/dist/4-object-basics.html"
                  >4. Объекты: основы</a
                >
                <a class="dropdown-item" href="/dist/5-data-types.html"
                  >5. Типы данных</a
                >
                <a class="dropdown-item" href="/dist/6-advanced-functions.html"
                  >6. Продвинутая работа с функциями</a
                >
                <a class="dropdown-item" href="/dist/7-object-properties.html"
                  >7. Свойства объекта, их конфигурация</a
                >
                <a class="dropdown-item" href="/dist/8-prototypes.html"
                  >8. Прототипы, наследование</a
                >
                <a class="dropdown-item" href="/dist/9-classes.html"
                  >9. Классы</a
                >
                <a class="dropdown-item" href="/dist/10-error-handling.html"
                  >10. Обработка ошибок</a
                >
                <a class="dropdown-item" href="/dist/11-async.html"
                  >11. Промисы, async/await</a
                >
                <a class="dropdown-item" href="/dist/12-generators-iterators.html"
                  >12. Генераторы, продвинутая итерация</a
                >
                <a class="dropdown-item" href="/dist/13-modules.html"
                  >13. Модули</a
                >
                <a class="dropdown-item" href="/dist/_3-6-network.html"
                  >3-6. Сетевые запросы</a
                >
              </div>
            </li>

<li class="nav-item dropdown">
  <a
    class="nav-link dropdown-toggle"
    href="#"
    id="navbarDropdownMenuLink"
    role="button"
    data-toggle="dropdown"
    aria-haspopup="true"
    aria-expanded="false"
    >Обработка ошибок</a
  >
  <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
    <a class="dropdown-item" href="#try-catch"
      >10.1 Обработка ошибок, "try..catch"</a
    >
    <a class="dropdown-item" href="#custom-errors"
      >10.2 Пользовательские ошибки, расширение Error</a
    >
  </div>
</li>

</ul>
</div>
</div>
</nav>

<!-- content -->
<div class="container mt-5">
  <h1>Обработка ошибок</h1>
  <div class="card mb-3" id="#try-catch">
    <div class="card-header d-flex align-items-center">
      <h2 class="h5 mb-0">10.1 Обработка ошибок, "try..catch"</h2>
      <div class="ml-auto">
        <a href="https://learn.javascript.ru/try-catch" target="_blank">Link</a>
      </div>
    </div>
    <div class="card-body">
      <p>
        Конструкция <code>try..catch</code> позволяет обрабатывать ошибки во
        время исполнения кода. Она позволяет запустить код и перехватить ошибки,
        которые могут в нём возникнуть.
      </p>
      <p>Синтаксис:</p>
      <pre><code>try {
  // исполняем код
} catch(err) {
  // если случилась ошибка, прыгаем сюда
  // err - это объект ошибки
} finally {
  // выполняется всегда после try/catch
}

let json = "{ некорректный JSON }";

try {

  let user = JSON.parse(json); // <-- тут возникает ошибка...
  alert( user.name ); // не сработает

} catch (e) {
  // ...выполнение прыгает сюда
  alert( "Извините, в данных ошибка, мы попробуем получить их ещё раз." );
  alert( e.name );
  alert( e.message );
}</code></pre>
      <p>
        Секций <code>catch</code> или <code>finally</code> может не быть, то
        есть более короткие конструкции <code>try..catch</code> и
        <code>try..finally</code> также корректны. Блок finally срабатывает при
        любом выходе из try..catch, в том числе и return.
      </p>
      <pre><code>try {
  alert( 'try' );
  if (confirm('Сгенерировать ошибку?')) BAD_CODE();
} catch (e) {
  alert( 'catch' );
} finally {
  alert( 'finally' );
}</code></pre>
      <p>Объекты ошибок содержат следующие свойства:</p>
      <ul>
        <li><code>message</code> – понятное человеку сообщение.</li>
        <li>
          <code>name</code> – строка с именем ошибки (имя конструктора ошибки).
        </li>
        <li>
          <code>stack</code> (нестандартное, но хорошо поддерживается) – стек на
          момент ошибки.
        </li>
      </ul>
      <p>
        Если объект ошибки не нужен, мы можем пропустить его, используя
        <code>catch {</code> вместо <code>catch(err) {</code>.
      </p>
      <p>
        Мы можем также генерировать собственные ошибки, используя оператор
        <code>throw</code>. Аргументом <code>throw</code> может быть что угодно,
        но обычно это объект ошибки, наследуемый от встроенного класса
        <code>Error</code>. Подробнее о расширении ошибок см. в следующей главе.
      </p>
      <pre><code>let json = '{ "age": 30 }'; // данные неполны

try {

  let user = JSON.parse(json); // <-- выполнится без ошибок

  if (!user.name) {
    throw new SyntaxError("Данные неполны: нет имени"); // (*)
  }

  alert( user.name );

} catch(e) {
  alert( "JSON Error: " + e.message ); // JSON Error: Данные неполны: нет имени
}</code></pre>
      <p>
        <em>Проброс исключения</em> – это очень важный приём обработки ошибок:
        блок <code>catch</code> обычно ожидает и знает, как обработать
        определённый тип ошибок, поэтому он должен пробрасывать дальше ошибки, о
        которых он не знает.
      </p>
      <p>
        <strong>try..catch работает синхронно</strong> Исключение, которое
        произойдёт в коде, запланированном «на будущее», например в setTimeout,
        try..catch не поймает. Это потому, что функция выполняется позже, когда
        движок уже покинул конструкцию try..catch. Чтобы поймать исключение
        внутри запланированной функции, try..catch должен находиться внутри
        самой этой функции
      </p>
      <p>
        Даже если у нас нет <code>try..catch</code>, большинство сред позволяют
        настроить «глобальный» обработчик ошибок, чтобы ловить ошибки, которые
        «выпадают наружу». В браузере это <code>window.onerror</code>.
      </p>
    </div>
  </div>
  <div class="card mb-3" id="#custom-errors">
    <div class="card-header d-flex align-items-center">
      <h2 class="h5 mb-0">10.2 Пользовательские ошибки, расширение Error</h2>
      <div class="dropdown ml-auto">
        <button
          class="btn btn-primary dropdown-toggle"
          type="button"
          id="dropdownMenuButton1"
          data-toggle="dropdown"
          aria-haspopup="true"
          aria-expanded="false"
        >
          Homeworks
        </button>
        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
          <a
            class="dropdown-item"
            target="_blank"
            href="./homeworks/10/10-2-1.html"
            >1</a
          >
        </div>
      </div>
      <div class="ml-4">
        <a href="https://learn.javascript.ru/custom-errors" target="_blank"
          >Link</a
        >
      </div>
    </div>
    <div class="card-body">
      <ul>
        <li>
          Мы можем наследовать свои классы ошибок от <code>Error</code> и других
          встроенных классов ошибок, но нужно позаботиться о свойстве
          <code>name</code> и не забыть вызвать <code>super</code>.
          <pre><code>class ValidationError extends Error {
  constructor(message) {
    super(message); // (1)
    this.name = "ValidationError"; // (2)
  }
}

function test() {
  throw new ValidationError("Упс!");
}

try {
  test();
} catch(err) {
  alert(err.message); // Упс!
  alert(err.name); // ValidationError
  alert(err.stack); // список вложенных вызовов с номерами строк для каждого
}</code></pre>
        </li>
        <li>
          Мы можем использовать <code>instanceof</code> для проверки типа
          ошибок. Это также работает с наследованием. Но иногда у нас объект
          ошибки, возникшей в сторонней библиотеке, и нет простого способа
          получить класс. Тогда для проверки типа ошибки можно использовать
          свойство <code>name</code>.
        </li>
        <li>
          Обёртывание исключений является распространённой техникой: функция
          ловит низкоуровневые исключения и создаёт одно «высокоуровневое»
          исключение вместо разных низкоуровневых. Иногда низкоуровневые
          исключения становятся свойствами этого объекта, как
          <code>err.cause</code> в примерах выше, но это не обязательно.
        </li>
      </ul>
      <pre><code>class ReadError extends Error {
  constructor(message, cause) {
    super(message);
    this.cause = cause;
    this.name = 'ReadError';
  }
}

class ValidationError extends Error { /*...*/ }
class PropertyRequiredError extends ValidationError { /* ... */ }

function validateUser(user) {
  if (!user.age) {
    throw new PropertyRequiredError("age");
  }

  if (!user.name) {
    throw new PropertyRequiredError("name");
  }
}

function readUser(json) {
  let user;

  try {
    user = JSON.parse(json);
  } catch (err) {
    if (err instanceof SyntaxError) {
      throw new ReadError("Синтаксическая ошибка", err);
    } else {
      throw err;
    }
  }

  try {
    validateUser(user);
  } catch (err) {
    if (err instanceof ValidationError) {
      throw new ReadError("Ошибка валидации", err);
    } else {
      throw err;
    }
  }

}

try {
  readUser('{bad json}');
} catch (e) {
  if (e instanceof ReadError) {
    alert(e);
    // Исходная ошибка: SyntaxError:Unexpected token b in JSON at position 1
    alert("Исходная ошибка: " + e.cause);
  } else {
    throw e;
  }
}</code></pre>
    </div>
  </div>
</div>

<!-- content -->
<!-- footer -->
</body>
</html>
